EcsAgentManagerBundle_homepage:
    pattern:  /agentmanager
    defaults: { _controller: EcsAgentManagerBundle:Default:index }
#EcsAgentManagerBundle_empositions:
#    resource: "@EcsAgentManagerBundle/Resources/config/routing/jobTitle.yml"
#    prefix:   /emjobTitles