EcsAgentManagerBundle_homepage:
    pattern:  /
    defaults: { _controller: EcsAgentManagerBundle:Default:index }
EcsAgentManagerBundle_agents:
    resource: "@EcsAgentManagerBundle/Resources/config/routing/user.yml"
    prefix:   /agentmanager